import type { Metadata } from 'next';
import { Oswald } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { Suspense } from 'react';
import { Loading } from '@/components/shared';
import DefaultLayout from '@/components/layouts/default-layout';

const oswald = Oswald({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-oswald',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={cn(oswald.variable, oswald.className, 'antialiased')}>
        <Suspense fallback={<Loading />}>
          <DefaultLayout>{children}</DefaultLayout>
        </Suspense>
      </body>
    </html>
  );
}
