export const countries = [
  'AL',
  'AD',
  'AR',
  'AU',
  'AT',
  'BE',
  'BA',
  'BR',
  'BG',
  'CA',
  'CL',
  'CO',
  'CR',
  'HR',
  'CZ',
  'DK',
  'EE',
  'FI',
  'FR',
  'DE',
  'GI',
  'GR',
  'HU',
  'IS',
  'IE',
  'IL',
  'IT',
  'JP',
  'LV',
  'LI',
  'LT',
  'MK',
  'MT',
  'MX',
  'MD',
  'MC',
  'ME',
  'NL',
  'NZ',
  'NO',
  'PE',
  'PL',
  'PT',
  'PR',
  'RO',
  'SM',
  'RS',
  'SG',
  'SK',
  'SI',
  'ZA',
  'KR',
  'ES',
  'SE',
  'CH',
  'UA',
  'GB',
  'US',
  'VI',
];

export const countryStateMap = {
  AL: [
    'Berat',
    'Dibër',
    'Durrës',
    'Elbasan',
    'Fier',
    'Gjirokastër',
    'Korçë',
    'Kukës',
    'Lezhë',
    'Shkodër',
    'Tirana',
    'Vlorë',
  ],
  AD: [
    'Andorra la Vella',
    'Canillo',
    'Encamp',
    'Escaldes-Engordany',
    'La Massana',
    'Ordino',
    'Sant Julià de Lòria',
  ],
  AR: [
    'Buenos Aires',
    'Catamarca',
    'Chaco',
    'Chubut',
    'Córdoba',
    'Corrientes',
    'Entre Ríos',
    'Formosa',
    'Jujuy',
    'La Pampa',
    'La Rioja',
    'Mendoza',
    'Misiones',
    'Neuquén',
    'Río Negro',
    'Salta',
    'San Juan',
    'San Luis',
    'Santa Cruz',
    'Santa Fe',
    'Santiago del Estero',
    'Tierra del Fuego',
    'Tucumán',
  ],
  AU: [
    'New South Wales',
    'Queensland',
    'Victoria',
    'Western Australia',
    'South Australia',
    'Tasmania',
    'Australian Capital Territory',
    'Northern Territory',
  ],
  AT: [
    'Burgenland',
    'Carinthia',
    'Lower Austria',
    'Upper Austria',
    'Salzburg',
    'Styria',
    'Tyrol',
    'Vorarlberg',
    'Vienna',
  ],
  BE: [
    'Antwerp',
    'East Flanders',
    'Flemish Brabant',
    'Hainaut',
    'Liège',
    'Limburg',
    'Luxembourg',
    'Namur',
    'Walloon Brabant',
    'West Flanders',
  ],
  BA: [
    'Brčko District',
    'Federation of Bosnia and Herzegovina',
    'Republika Srpska',
  ],
  BR: [
    'SP Capital & Metro Area',
    'SP Interior',
    'RJ Capital & Metro Area',
    'RJ Interior & ES',
    'MG Capital & Metro Area',
    'MG Interior',
    'BA Capital & Metro Area',
    'BA Interior, SE, & Sede Recife',
    'PR Capital & Metro Area',
    'PR Interior, SC, & RS Interior',
    'RS Capital & Metro Area',
    'Sede Fortaleza & Sede Brasilia',
  ],
  BG: [
    'Blagoevgrad',
    'Burgas',
    'Dobrich',
    'Gabrovo',
    'Haskovo',
    'Kardzhali',
    'Kyustendil',
    'Lovech',
    'Montana',
    'Pazardzhik',
    'Pernik',
    'Pleven',
    'Plovdiv',
    'Razgrad',
    'Ruse',
    'Shumen',
    'Silistra',
    'Sliven',
    'Smolyan',
    'Sofia',
    'Sofia City',
    'Stara Zagora',
    'Targovishte',
    'Varna',
    'Veliko Tarnovo',
    'Vidin',
    'Vratsa',
    'Yambol',
  ],
  CA: [
    'Alberta',
    'British Columbia',
    'Manitoba',
    'New Brunswick',
    'Newfoundland and Labrador',
    'Northwest Territories',
    'Nova Scotia',
    'Nunavut',
    'Ontario',
    'Prince Edward Island',
    'Quebec',
    'Saskatchewan',
    'Yukon',
  ],
  CL: [
    'Antofagasta',
    'Arica y Parinacota',
    'Atacama',
    'Aysén del General Carlos Ibáñez del Campo',
    'Biobío',
    'Coquimbo',
    'La Araucanía',
    "Libertador General Bernardo O'Higgins",
    'Los Lagos',
    'Los Ríos',
    'Magallanes y de la Antártica Chilena',
    'Maule',
    'Metropolitana de Santiago',
    'Ñuble',
    'Tarapacá',
    'Valparaíso',
  ],
  CO: [
    'Amazonas',
    'Antioquia',
    'Arauca',
    'Atlántico',
    'Bogotá',
    'Bolívar',
    'Boyacá',
    'Caldas',
    'Caquetá',
    'Casanare',
    'Cauca',
    'Cesar',
    'Chocó',
    'Córdoba',
    'Cundinamarca',
    'Guainía',
    'Guaviare',
    'Huila',
    'La Guajira',
    'Magdalena',
    'Meta',
    'Nariño',
    'Norte de Santander',
    'Putumayo',
    'Quindío',
    'Risaralda',
    'San Andrés y Providencia',
    'Santander',
    'Sucre',
    'Tolima',
    'Valle del Cauca',
    'Vaupés',
    'Vichada',
  ],
  CR: [
    'Alajuela',
    'Cartago',
    'Guanacaste',
    'Heredia',
    'Limón',
    'Puntarenas',
    'San José',
  ],
  HR: [
    'Bjelovar-Bilogora',
    'Brod-Posavina',
    'Dubrovnik-Neretva',
    'Istria',
    'Karlovac',
    'Koprivnica-Križevci',
    'Krapina-Zagorje',
    'Lika-Senj',
    'Međimurje',
    'Osijek-Baranja',
    'Požega-Slavonia',
    'Primorje-Gorski Kotar',
    'Šibenik-Knin',
    'Sisak-Moslavina',
    'Split-Dalmatia',
    'Varaždin',
    'Virovitica-Podravina',
    'Vukovar-Syrmia',
    'Zadar',
    'Zagreb County',
    'City of Zagreb',
  ],
  CZ: [
    'Central Bohemian',
    'South Bohemian',
    'Plzeň',
    'Karlovy Vary',
    'Ústí nad Labem',
    'Liberec',
    'Hradec Králové',
    'Pardubice',
    'Vysočina',
    'South Moravian',
    'Olomouc',
    'Zlín',
    'Moravian-Silesian',
    'Prague',
  ],
  DK: ['Greenland', 'Bornholm', 'Faroe Islands', 'Samso'],
  EE: [
    'Harju',
    'Hiiu',
    'Ida-Viru',
    'Jõgeva',
    'Järva',
    'Lääne',
    'Lääne-Viru',
    'Põlva',
    'Pärnu',
    'Rapla',
    'Saare',
    'Tartu',
    'Valga',
    'Viljandi',
    'Võru',
  ],
  FI: [
    'Åland Islands',
    'Central Finland',
    'Central Ostrobothnia',
    'Finland Proper',
    'Kainuu',
    'Kanta-Häme',
    'Kymenlaakso',
    'Lapland',
    'North Karelia',
    'Northern Ostrobothnia',
    'Northern Savonia',
    'Ostrobothnia',
    'Päijät-Häme',
    'Pirkanmaa',
    'Satakunta',
    'South Karelia',
    'Southern Ostrobothnia',
    'Southern Savonia',
    'Uusimaa',
  ],
  FR: [
    'Corsica',
    'French Guiana',
    'French Polynesia',
    'Guadeloupe',
    'Martinique',
    'Mayotte',
    'New Caledonia',
    'Saint Martin',
    'Saint Pierre & Miquelon',
    'Wallis & Futuna',
  ],
  DE: [
    'Baden-Württemberg',
    'Bavaria',
    'Berlin',
    'Brandenburg',
    'Bremen',
    'Hamburg',
    'Hesse',
    'Lower Saxony',
    'Mecklenburg-Vorpommern',
    'North Rhine-Westphalia',
    'Rhineland-Palatinate',
    'Saarland',
    'Saxony',
    'Saxony-Anhalt',
    'Schleswig-Holstein',
    'Thuringia',
  ],
  GI: ['Gibraltar'],
  GR: [
    'Achaea',
    'Aetolia-Acarnania',
    'Arcadia',
    'Argolis',
    'Attica',
    'Boeotia',
    'Chalkidiki',
    'Chania',
    'Corfu',
    'Cyclades',
    'Dodecanese',
    'Drama',
    'East Attica',
    'Euboea',
    'Florina',
    'Grevena',
    'Imathia',
    'Ioannina',
    'Karditsa',
    'Kastoria',
    'Kavala',
    'Kefalonia',
    'Kilkis',
    'Kozani',
    'Laconia',
    'Larissa',
    'Lasithi',
    'Lefkada',
    'Messenia',
    'Pella',
    'Phthiotis',
    'Pieria',
    'Preveza',
    'Rethymno',
    'Rhodope',
    'Serres',
    'Thessaloniki',
    'Trikala',
    'West Attica',
    'Xanthi',
    'Zakynthos',
  ],
  HU: [
    'Bács-Kiskun',
    'Baranya',
    'Békés',
    'Borsod-Abaúj-Zemplén',
    'Budapest',
    'Csongrád-Csanád',
    'Fejér',
    'Győr-Moson-Sopron',
    'Hajdú-Bihar',
    'Heves',
    'Jász-Nagykun-Szolnok',
    'Komárom-Esztergom',
    'Nógrád',
    'Pest',
    'Somogy',
    'Szabolcs-Szatmár-Bereg',
    'Tolna',
    'Vas',
    'Veszprém',
    'Zala',
  ],
  IS: [
    'Capital Region',
    'Southern Peninsula',
    'West',
    'Westfjords',
    'Northwest',
    'Northeast',
    'East',
    'South',
  ],
  IE: [
    'Carlow',
    'Cavan',
    'Clare',
    'Cork',
    'Donegal',
    'Dublin',
    'Galway',
    'Kerry',
    'Kildare',
    'Kilkenny',
    'Laois',
    'Leitrim',
    'Limerick',
    'Longford',
    'Louth',
    'Mayo',
    'Meath',
    'Monaghan',
    'Offaly',
    'Roscommon',
    'Sligo',
    'Tipperary',
    'Waterford',
    'Westmeath',
    'Wexford',
    'Wicklow',
  ],
  IL: [
    'Central District',
    'Haifa District',
    'Jerusalem District',
    'Northern District',
    'Southern District',
    'Tel Aviv District',
  ],
  IT: [
    'Abruzzo',
    'Aosta Valley',
    'Apulia',
    'Basilicata',
    'Calabria',
    'Campania',
    'Emilia-Romagna',
    'Friuli Venezia Giulia',
    'Lazio',
    'Liguria',
    'Lombardy',
    'Marche',
    'Molise',
    'Piedmont',
    'Sardinia',
    'Sicily',
    'Trentino-South Tyrol',
    'Tuscany',
    'Umbria',
    'Veneto',
  ],
  JP: [
    'Aichi',
    'Akita',
    'Aomori',
    'Chiba',
    'Ehime',
    'Fukui',
    'Fukuoka',
    'Fukushima',
    'Gifu',
    'Gunma',
    'Hiroshima',
    'Hokkaido',
    'Hyogo',
    'Ibaraki',
    'Ishikawa',
    'Iwate',
    'Kagawa',
    'Kagoshima',
    'Kanagawa',
    'Kochi',
    'Kumamoto',
    'Kyoto',
    'Mie',
    'Miyagi',
    'Miyazaki',
    'Nagano',
    'Nagasaki',
    'Nara',
    'Niigata',
    'Oita',
    'Okayama',
    'Okinawa',
    'Osaka',
    'Saga',
    'Saitama',
    'Shiga',
    'Shimane',
    'Shizuoka',
    'Tochigi',
    'Tokushima',
    'Tokyo',
    'Tottori',
    'Toyama',
    'Wakayama',
    'Yamagata',
    'Yamaguchi',
    'Yamanashi',
  ],
  LV: ['Kurzeme', 'Latgale', 'Riga', 'Vidzeme', 'Zemgale'],
  LI: [
    'Balzers',
    'Eschen',
    'Gamprin',
    'Mauren',
    'Planken',
    'Ruggell',
    'Schaan',
    'Schellenberg',
    'Triesen',
    'Triesenberg',
    'Vaduz',
  ],
  LT: [
    'Alytus County',
    'Kaunas County',
    'Klaipėda County',
    'Marijampolė County',
    'Panevėžys County',
    'Šiauliai County',
    'Tauragė County',
    'Telšiai County',
    'Utena County',
    'Vilnius County',
  ],
  LU: [
    'Canton of Capellen',
    'Canton of Clervaux',
    'Canton of Diekirch',
    'Canton of Echternach',
    'Canton of Esch-sur-Alzette',
    'Canton of Grevenmacher',
    'Canton of Luxembourg',
    'Canton of Mersch',
    'Canton of Redange',
    'Canton of Remich',
    'Canton of Vianden',
    'Canton of Wiltz',
  ],
  MK: [
    'Eastern',
    'Northeastern',
    'Pelagonia',
    'Polog',
    'Skopje',
    'Southeastern',
    'Southwestern',
    'Vardar',
  ],
  MT: ['Gozo', 'Malta'],
  MD: [
    'Anenii Noi',
    'Bălți',
    'Basarabeasca',
    'Bender',
    'Briceni',
    'Cahul',
    'Cantemir',
    'Călărași',
    'Căușeni',
    'Chișinău',
    'Cimișlia',
    'Criuleni',
    'Dondușeni',
    'Drochia',
    'Dubăsari',
    'Edineț',
    'Fălești',
    'Florești',
    'Gagauzia',
    'Glodeni',
    'Hîncești',
    'Ialoveni',
    'Leova',
    'Nisporeni',
    'Ocnița',
    'Orhei',
    'Rezina',
    'Rîșcani',
    'Sîngerei',
    'Șoldănești',
    'Soroca',
    'Ștefan Vodă',
    'Strășeni',
    'Taraclia',
    'Telenești',
    'Transnistria',
    'Ungheni',
  ],
  MC: ['La Condamine', 'Fontvieille', 'Monaco-Ville', 'Monte Carlo'],
  ME: [
    'Andrijevica',
    'Bar',
    'Berane',
    'Bijelo Polje',
    'Budva',
    'Cetinje',
    'Danilovgrad',
    'Gusinje',
    'Herceg Novi',
    'Kolašin',
    'Kotor',
    'Mojkovac',
    'Nikšić',
    'Petnjica',
    'Plav',
    'Plužine',
    'Pljevlja',
    'Podgorica',
    'Rožaje',
    'Šavnik',
    'Tivat',
    'Tuzi',
    'Ulcinj',
    'Žabljak',
  ],
  NL: [
    'Drenthe',
    'Flevoland',
    'Friesland',
    'Gelderland',
    'Groningen',
    'Limburg',
    'North Brabant',
    'North Holland',
    'Overijssel',
    'South Holland',
    'Utrecht',
    'Zeeland',
  ],
  NZ: [
    'Auckland',
    'Bay of Plenty',
    'Canterbury',
    'Gisborne',
    "Hawke's Bay",
    'Manawatū-Whanganui',
    'Marlborough',
    'Nelson',
    'Northland',
    'Otago',
    'Southland',
    'Taranaki',
    'Tasman',
    'Waikato',
    'Wellington',
    'West Coast',
  ],
  NO: [
    'Agder',
    'Innlandet',
    'Møre og Romsdal',
    'Nordland',
    'Oslo',
    'Rogaland',
    'Troms og Finnmark',
    'Trøndelag',
    'Vestfold og Telemark',
    'Vestland',
    'Viken',
  ],
  PE: [
    'Amazonas',
    'Áncash',
    'Apurímac',
    'Arequipa',
    'Ayacucho',
    'Cajamarca',
    'Callao',
    'Cusco',
    'Huancavelica',
    'Huánuco',
    'Ica',
    'Junín',
    'La Libertad',
    'Lambayeque',
    'Lima',
    'Loreto',
    'Madre de Dios',
    'Moquegua',
    'Pasco',
    'Piura',
    'Puno',
    'San Martín',
    'Tacna',
    'Tumbes',
    'Ucayali',
  ],
  PL: [
    'Greater Poland',
    'Kuyavian-Pomeranian',
    'Lesser Poland',
    'Łódź',
    'Lower Silesian',
    'Lublin',
    'Lubusz',
    'Masovian',
    'Opole',
    'Podlaskie',
    'Pomeranian',
    'Silesian',
    'Subcarpathian',
    'Świętokrzyskie',
    'Warmian-Masurian',
    'West Pomeranian',
  ],
  PT: ['Azores', 'Madeira'],
  PR: [
    'Adjuntas',
    'Aguada',
    'Aguadilla',
    'Aguas Buenas',
    'Aibonito',
    'Añasco',
    'Arecibo',
    'Arroyo',
    'Barceloneta',
    'Barranquitas',
    'Bayamón',
    'Cabo Rojo',
    'Caguas',
    'Camuy',
    'Canóvanas',
    'Carolina',
    'Cataño',
    'Cayey',
    'Ceiba',
    'Ciales',
    'Cidra',
    'Coamo',
    'Comerío',
    'Corozal',
    'Culebra',
    'Dorado',
    'Fajardo',
    'Florida',
    'Guánica',
    'Guayama',
    'Guayanilla',
    'Guaynabo',
    'Gurabo',
    'Hatillo',
    'Hormigueros',
    'Humacao',
    'Isabela',
    'Jayuya',
    'Juana Díaz',
    'Juncos',
    'Lajas',
    'Lares',
    'Las Marías',
    'Las Piedras',
    'Loíza',
    'Luquillo',
    'Manatí',
    'Maricao',
    'Maunabo',
    'Mayagüez',
    'Moca',
    'Morovis',
    'Naguabo',
    'Naranjito',
    'Orocovis',
    'Patillas',
    'Peñuelas',
    'Ponce',
    'Quebradillas',
    'Rincón',
    'Río Grande',
    'Sabana Grande',
    'Salinas',
    'San Germán',
    'San Juan',
    'San Lorenzo',
    'San Sebastián',
    'Santa Isabel',
    'Toa Alta',
    'Toa Baja',
    'Trujillo Alto',
    'Utuado',
    'Vega Alta',
    'Vega Baja',
    'Vieques',
    'Villalba',
    'Yabucoa',
    'Yauco',
  ],
  RO: [
    'Alba',
    'Arad',
    'Argeș',
    'Bacău',
    'Bihor',
    'Bistrița-Năsăud',
    'Botoșani',
    'Brăila',
    'Brașov',
    'Bucharest',
    'Buzău',
    'Călărași',
    'Caraș-Severin',
    'Cluj',
    'Constanța',
    'Covasna',
    'Dâmbovița',
    'Dolj',
    'Galați',
    'Giurgiu',
    'Gorj',
    'Harghita',
    'Hunedoara',
    'Ialomița',
    'Iași',
    'Ilfov',
    'Maramureș',
    'Mehedinți',
    'Mureș',
    'Neamț',
    'Olt',
    'Prahova',
    'Sălaj',
    'Satu Mare',
    'Sibiu',
    'Suceava',
    'Teleorman',
    'Timiș',
    'Tulcea',
    'Vâlcea',
    'Vaslui',
    'Vrancea',
  ],
  SM: [
    'Acquaviva',
    'Borgo Maggiore',
    'Chiesanuova',
    'Domagnano',
    'Faetano',
    'Fiorentino',
    'Montegiardino',
    'San Marino',
    'Serravalle',
  ],
  RS: [
    'Belgrade',
    'Bor',
    'Braničevo',
    'Central Banat',
    'Jablanica',
    'Kolubara',
    'Mačva',
    'Moravica',
    'Nišava',
    'North Bačka',
    'North Banat',
    'Pčinja',
    'Pirot',
    'Podunavlje',
    'Pomoravlje',
    'Rasina',
    'Raška',
    'South Bačka',
    'South Banat',
    'Srem',
    'Šumadija',
    'Toplica',
    'West Bačka',
    'Zaječar',
    'Zlatibor',
  ],
  SG: [
    'Central Singapore',
    'North East',
    'North West',
    'South East',
    'South West',
  ],
  SK: [
    'Banská Bystrica',
    'Bratislava',
    'Košice',
    'Nitra',
    'Prešov',
    'Trenčín',
    'Trnava',
    'Žilina',
  ],
  SI: [
    'Ajdovščina',
    'Beltinci',
    'Bled',
    'Bohinj',
    'Borovnica',
    'Bovec',
    'Brda',
    'Brezovica',
    'Brežice',
    'Cankova',
    'Celje',
    'Cerklje na Gorenjskem',
    'Cerknica',
    'Cerkno',
    'Cerkvenjak',
    'City Municipality of Slovenj Gradec',
    'Črenšovci',
    'Črna na Koroškem',
    'Črnomelj',
    'Destrnik',
    'Divača',
    'Dobje',
    'Dobrepolje',
    'Dobrna',
    'Dobrova-Polhov Gradec',
    'Dobrovnik',
    'Dolenjske Toplice',
    'Dol pri Ljubljani',
    'Domžale',
    'Dornava',
    'Dravograd',
    'Duplek',
    'Gorenja Vas-Poljane',
    'Gorišnica',
    'Gorje',
    'Gornja Radgona',
    'Gornji Grad',
    'Gornji Petrovci',
    'Grad',
    'Grosuplje',
    'Hajdina',
    'Hoče-Slivnica',
    'Hodoš',
    'Horjul',
    'Hrastnik',
    'Hrpelje-Kozina',
    'Idrija',
    'Ig',
    'Ilirska Bistrica',
    'Ivancna Gorica',
    'Izola',
    'Jesenice',
    'Jezersko',
    'Juršinci',
    'Kamnik',
    'Kanal ob Soči',
    'Kidričevo',
    'Kobarid',
    'Kobilje',
    'Kočevje',
    'Komen',
    'Komenda',
    'Koper',
    'Kostanjevica na Krki',
    'Kostel',
    'Kozje',
    'Kranj',
    'Kranjska Gora',
    'Križevci',
    'Kuzma',
    'Laško',
    'Lenart',
    'Lendava',
    'Litija',
    'Ljubljana',
    'Ljubno',
    'Ljutomer',
    'Logatec',
    'Log-Dragomer',
    'Loška Dolina',
    'Loški Potok',
    'Lovrenc na Pohorju',
    'Luče',
    'Lukovica',
    'Majšperk',
    'Makole',
    'Maribor',
    'Markovci',
    'Medvode',
    'Mengeš',
    'Metlika',
    'Mežica',
    'Miklavž na Dravskem Polju',
    'Miren-Kostanjevica',
    'Mirna',
    'Mirna Peč',
    'Mislinja',
    'Mokronog-Trebelno',
    'Moravče',
    'Moravske Toplice',
    'Mozirje',
    'Murska Sobota',
    'Muta',
    'Naklo',
    'Nazarje',
    'Nova Gorica',
    'Novo Mesto',
    'Odranci',
    'Oplotnica',
    'Ormož',
    'Osilnica',
    'Pesnica',
    'Piran',
    'Pivka',
    'Podčetrtek',
    'Podlehnik',
    'Podvelka',
    'Poljčane',
    'Polzela',
    'Postojna',
    'Prebold',
    'Preddvor',
    'Prevalje',
    'Ptuj',
    'Puconci',
    'Rače-Fram',
    'Radeče',
    'Radenci',
    'Radlje ob Dravi',
    'Radovljica',
    'Ravne na Koroškem',
    'Razkrižje',
    'Renče-Vogrsko',
    'Ribnica',
    'Ribnica na Pohorju',
    'Rogaška Slatina',
    'Rogašovci',
    'Rogatec',
    'Ruše',
    'Šalovci',
    'Šempeter-Vrtojba',
    'Šenčur',
    'Šentilj',
    'Šentjernej',
    'Šentjur',
    'Šentrupert',
    'Sevnica',
    'Sežana',
    'Škocjan',
    'Škofja Loka',
    'Škofljica',
    'Slovenj Gradec',
    'Slovenska Bistrica',
    'Slovenske Konjice',
    'Šmarje pri Jelšah',
    'Šmarješke Toplice',
    'Šmartno ob Paki',
    'Šmartno pri Litiji',
    'Šoštanj',
    'Štore',
    'Straža',
    'Sveta Ana',
    'Sveta Trojica v Slovenskih Goricah',
    'Sveti Andraž v Slovenskih Goricah',
    'Sveti Jurij ob Ščavnici',
    'Sveti Jurij v Slovenskih Goricah',
    'Sveti Tomaž',
    'Tabor',
    'Tišina',
    'Tolmin',
    'Trbovlje',
    'Trebnje',
    'Trnovska Vas',
    'Trzin',
    'Turnišče',
    'Velenje',
    'Velika Polana',
    'Velike Lašče',
    'Veržej',
    'Videm',
    'Vipava',
    'Vitanje',
    'Vodice',
    'Vojnik',
    'Vransko',
    'Vrhnika',
    'Vuzenica',
    'Zagorje ob Savi',
    'Žalec',
    'Železniki',
    'Žetale',
    'Žiri',
    'Žirovnica',
    'Žužemberk',
    'Zreče',
  ],
  ZA: [
    'Eastern Cape',
    'Free State',
    'Gauteng',
    'KwaZulu-Natal',
    'Limpopo',
    'Mpumalanga',
    'North West',
    'Northern Cape',
    'Western Cape',
  ],
  KR: [
    'Busan',
    'Chungbuk',
    'Chungnam',
    'Daegu',
    'Daejeon',
    'Gangwon',
    'Gwangju',
    'Gyeongbuk',
    'Gyeonggi',
    'Gyeongnam',
    'Incheon',
    'Jeju',
    'Jeonbuk',
    'Jeonnam',
    'Sejong',
    'Seoul',
    'Ulsan',
  ],
  ES: ['Balearic Islands', 'Canary Islands'],
  SE: [
    'Blekinge',
    'Dalarna',
    'Gävleborg',
    'Gotland',
    'Halland',
    'Jämtland',
    'Jönköping',
    'Kalmar',
    'Kronoberg',
    'Norrbotten',
    'Örebro',
    'Östergötland',
    'Skåne',
    'Södermanland',
    'Stockholm',
    'Uppsala',
    'Värmland',
    'Västerbotten',
    'Västernorrland',
    'Västmanland',
    'Västra Götaland',
  ],
  CH: [
    'Aargau',
    'Appenzell Ausserrhoden',
    'Appenzell Innerrhoden',
    'Basel-Landschaft',
    'Basel-Stadt',
    'Bern',
    'Fribourg',
    'Geneva',
    'Glarus',
    'Graubünden',
    'Jura',
    'Luzern',
    'Neuchâtel',
    'Nidwalden',
    'Obwalden',
    'Schaffhausen',
    'Schwyz',
    'Solothurn',
    'St. Gallen',
    'Thurgau',
    'Ticino',
    'Uri',
    'Valais',
    'Vaud',
    'Zug',
    'Zürich',
  ],
  UA: [
    'Cherkasy',
    'Chernihiv',
    'Chernivtsi',
    'Dnipropetrovsk',
    'Donetsk',
    'Ivano-Frankivsk',
    'Kharkiv',
    'Kherson',
    'Khmelnytskyi',
    'Kirovohrad',
    'Kyiv',
    'Luhansk',
    'Lviv',
    'Mykolaiv',
    'Odessa',
    'Poltava',
    'Rivne',
    'Sumy',
    'Ternopil',
    'Vinnytsia',
    'Volyn',
    'Zakarpattia',
    'Zaporizhzhia',
    'Zhytomyr',
  ],
  GB: ['England', 'Northern Ireland', 'Scotland', 'Wales'],
  US: [
    'Alabama',
    'Alaska',
    'American Samoa',
    'Arizona',
    'Arkansas',
    'Armed Forces the Americas',
    'Armed Forces Europe',
    'Armed Forces Pacific',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'Florida',
    'Georgia',
    'Guam',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Northern Mariana Islands',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming',
  ],
  VI: ['Saint Croix', 'Saint John', 'Saint Thomas'],
};

export const countryCodeToName = {
  AL: 'Albania',
  AD: 'Andorra',
  AR: 'Argentina',
  AU: 'Australia',
  AT: 'Austria',
  BE: 'Belgium',
  BA: 'Bosnia and Herzegovina',
  BR: 'Brazil',
  BG: 'Bulgaria',
  CA: 'Canada',
  CL: 'Chile',
  CO: 'Colombia',
  CR: 'Costa Rica',
  HR: 'Croatia',
  CZ: 'Czech Republic',
  DK: 'Denmark',
  EE: 'Estonia',
  FI: 'Finland',
  FR: 'France',
  DE: 'Germany',
  GI: 'Gibraltar',
  GR: 'Greece',
  HU: 'Hungary',
  IS: 'Iceland',
  IE: 'Ireland',
  IL: 'Israel',
  IT: 'Italy',
  JP: 'Japan',
  LV: 'Latvia',
  LI: 'Liechtenstein',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  MK: 'North Macedonia',
  MT: 'Malta',
  MX: 'Mexico',
  MD: 'Moldova',
  MC: 'Monaco',
  ME: 'Montenegro',
  NL: 'Netherlands',
  NZ: 'New Zealand',
  NO: 'Norway',
  PE: 'Peru',
  PL: 'Poland',
  PT: 'Portugal',
  PR: 'Puerto Rico',
  RO: 'Romania',
  SM: 'San Marino',
  RS: 'Serbia',
  SG: 'Singapore',
  SK: 'Slovakia',
  SI: 'Slovenia',
  ZA: 'South Africa',
  KR: 'South Korea',
  ES: 'Spain',
  SE: 'Sweden',
  CH: 'Switzerland',
  UA: 'Ukraine',
  GB: 'United Kingdom (Great Britain)',
  US: 'United States',
  VI: 'Virgin Islands, U.S.',
};
